spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import:
      - optional:classpath:/setting.yml


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: iamjyoungkim@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG


server:
  servlet:
    encoding:
      force-response: true


